### ISSUE TITLE
func_physboxes are acting very strange

### ISSUE THREAD

**Issue by DaaOtt** [DrChat/Gmod-vphysics#49]
http://a.pomf.se/rqzyfk.mp4

It's almost as if it's physics are only OBB, however when I noclip inside, I can walk away from it but not towards it. It also seems to stretch upwards a great deal.

**Comment by DrChat** [comment]
Can you create a map with a basic reproduction case?
That could just be the player's collision hull being traced against a trigger with a bad collision mask (my collision trace function doesn't have collision mask checking implemented yet either)

**Comment by DrChat** [comment]
Look at this issue again. Commit ad322a6d695448ee2aa66de9d4f651e7873e9231 may have affected this.

**Comment by DaaOtt** [comment]
It did.
